import { PrismaClient } from "@prisma/client";
import bcrypt from "bcryptjs";

const prisma = new PrismaClient();
async function main() {
  const animeIcons = await prisma.category.upsert({ where: { slug: "anime-icons" }, update: {}, create: { name: "Anime Icons", slug: "anime-icons", description: "Stylized character figures with painterly detail and big personality." } });
  const retroArcade = await prisma.category.upsert({ where: { slug: "retro-arcade" }, update: {}, create: { name: "Retro Arcade", slug: "retro-arcade", description: "Pixel-bright figures pulled straight from the golden age of the arcade." } });
  const spaceLegends = await prisma.category.upsert({ where: { slug: "space-legends" }, update: {}, create: { name: "Space Legends", slug: "space-legends", description: "Epic sci-fi explorers, droids, and starfarers built for the display shelf." } });
  const kaijuClub = await prisma.category.upsert({ where: { slug: "kaiju-club" }, update: {}, create: { name: "Kaiju Club", slug: "kaiju-club", description: "Giant monsters with surprisingly big hearts, sculpted in loving detail." } });
  const indieArtists = await prisma.category.upsert({ where: { slug: "indie-artists" }, update: {}, create: { name: "Indie Artists", slug: "indie-artists", description: "Small-batch art toys from independent sculptors, hand-finished and numbered." } });
  const miniIcons = await prisma.category.upsert({ where: { slug: "mini-icons" }, update: {}, create: { name: "Mini Icons", slug: "mini-icons", description: "Pocket-sized blind-box collectibles built for stacking shelves and surprise pulls." } });

  await Promise.all([
    // Anime Icons
    prisma.product.upsert({ where: { sku: "AIC-001" }, update: {}, create: { sku: "AIC-001", slug: "kestrel-the-wanderer", name: "Kestrel the Wanderer", description: "A hand-painted vinyl figure with a weathered cloak and articulated joints.", price: 4999, cost: 2200, stockQuantity: 32, categoryId: animeIcons.id, franchise: "Anime Icons", character: "Kestrel", edition: "Standard", releaseDate: new Date("2026-06-01"), badges: ["NEW"], characterStory: "Kestrel wanders between rival clans, trusted by none and needed by all.", funFacts: ["First figure in the Wanderer line", "Cloak fabric is a separate cloth piece, not sculpted plastic"], imageUrl: "https://images.unsplash.com/photo-1606663889134-b1dedb5ed8b7?auto=format&fit=crop&w=1000&q=80" } }),
    prisma.product.upsert({ where: { sku: "AIC-002" }, update: {}, create: { sku: "AIC-002", slug: "yuki-nightshade", name: "Yuki Nightshade", description: "A moonlit priestess figure cast in pearlescent resin, with a removable lantern accessory and hand-inked eye detailing.", price: 8999, cost: 4000, stockQuantity: 14, categoryId: animeIcons.id, franchise: "Anime Icons", character: "Yuki Nightshade", edition: "Deluxe", releaseDate: new Date("2026-04-14"), badges: ["LIMITED", "FAN_FAVORITE"], characterStory: "Yuki keeps watch over the boundary between the waking world and the dream realm, lighting the way for travelers who lose their path after dark. She speaks rarely, but every villager knows her lantern by sight.", funFacts: ["Lantern glows under blacklight", "Eyes are hand-painted individually, so no two figures match exactly", "Design grew out of more than 40 early concept sketches"], imageUrl: "https://images.unsplash.com/photo-1529335764857-3f1164d1cb24?auto=format&fit=crop&w=1000&q=80" } }),
    prisma.product.upsert({ where: { sku: "AIC-003" }, update: {}, create: { sku: "AIC-003", slug: "ronin-vale", name: "Ronin Vale", description: "An oversized katana-wielding swordsman figure with a swappable battle-worn faceplate and weathered fabric sash.", price: 14999, cost: 6800, stockQuantity: 8, categoryId: animeIcons.id, franchise: "Anime Icons", character: "Ronin Vale", edition: "Exclusive", releaseDate: new Date("2026-07-20"), badges: ["PRE_ORDER"], characterStory: "Ronin Vale swore an oath to a master who no longer exists, and now wanders battlefields looking for a fight worth the blade. Collectors call him the line's quiet fan favorite, for reasons nobody can quite explain.", funFacts: ["Includes two interchangeable expression faceplates", "Sash is tied by hand at the factory, not molded", "Pre-order units ship with a metallic blade variant"], imageUrl: "https://images.unsplash.com/photo-1623039978462-d01b0b1cad70?auto=format&fit=crop&w=1000&q=80" } }),

    // Retro Arcade
    prisma.product.upsert({ where: { sku: "RAR-001" }, update: {}, create: { sku: "RAR-001", slug: "byte-blaster", name: "Byte Blaster", description: "An 8-bit-inspired hero figure with blocky proportions, chunky primary colors, and a light-up chest core.", price: 3999, cost: 1700, stockQuantity: 40, categoryId: retroArcade.id, franchise: "Retro Arcade", character: "Byte Blaster", edition: "Standard", releaseDate: new Date("2026-03-10"), badges: ["NEW"], characterStory: "Byte Blaster was the first sprite to break out of his cabinet and into the real world, and he's never stopped grinning about it. He collects high scores the way other people collect trophies.", funFacts: ["Chest core lights up on a coin-cell battery", "Sculpt intentionally keeps visible pixel edges", "Based on a fictional 1991 arcade cabinet"], imageUrl: "https://images.unsplash.com/photo-1700909415800-6d2a5a83a234?auto=format&fit=crop&w=1000&q=80" } }),
    prisma.product.upsert({ where: { sku: "RAR-002" }, update: {}, create: { sku: "RAR-002", slug: "pixel-pup-zero", name: "Pixel Pup Zero", description: "A boxy companion-bot figure with articulated ears, a wagging tail joint, and a translucent chase-edition shell.", price: 5999, cost: 2600, stockQuantity: 6, categoryId: retroArcade.id, franchise: "Retro Arcade", character: "Pixel Pup Zero", edition: "Chase", releaseDate: new Date("2026-05-02"), badges: ["LIMITED", "FAN_FAVORITE"], characterStory: "Pixel Pup Zero was patched into existence as a debugging tool and immediately refused to leave. Now he rides shotgun with every hero in the arcade, mostly for the snacks.", funFacts: ["1-in-12 chase variant with a clear shell", "Tail joint is spring-loaded", "Named after an internal bug-tracker ticket number"], imageUrl: "https://images.unsplash.com/photo-1700909416178-40b292788200?auto=format&fit=crop&w=1000&q=80" } }),
    prisma.product.upsert({ where: { sku: "RAR-003" }, update: {}, create: { sku: "RAR-003", slug: "coin-king-cascade", name: "Coin King Cascade", description: "A crowned, coin-hoarding boss figure on a diorama base of stacked tokens, with a removable cape.", price: 8999, cost: 4100, stockQuantity: 15, categoryId: retroArcade.id, franchise: "Retro Arcade", character: "Coin King Cascade", edition: "Deluxe", releaseDate: new Date("2026-08-01"), badges: ["PRE_ORDER"], characterStory: "Coin King Cascade rules the arcade's high-score board through sheer stubbornness, refusing every challenger a rematch he might lose. Everyone wants to beat him. Nobody has.", funFacts: ["Diorama base includes 30 sculpted coin tokens", "Crown is die-cast metal, not plastic", "Cape hides a small compartment for a spare coin"], imageUrl: "https://images.unsplash.com/photo-1700825073852-1913b3886584?auto=format&fit=crop&w=1000&q=80" } }),

    // Space Legends
    prisma.product.upsert({ where: { sku: "SPL-001" }, update: {}, create: { sku: "SPL-001", slug: "captain-nova-vega", name: "Captain Nova Vega", description: "A fully articulated starship captain figure in a weathered flight suit, with a display-ready magnetic helmet.", price: 5999, cost: 2600, stockQuantity: 25, categoryId: spaceLegends.id, franchise: "Space Legends", character: "Nova Vega", edition: "Standard", releaseDate: new Date("2026-03-25"), badges: ["NEW"], characterStory: "Nova Vega has logged more deep-space hours than anyone in the fleet and still reads the safety briefing out loud before every single flight. Her crew calls it superstition. She calls it discipline.", funFacts: ["Helmet attaches magnetically for easy posing", "Flight suit weathering is airbrushed by hand", "22 points of articulation"], imageUrl: "https://images.unsplash.com/photo-1718254951230-dac05b0ff8b9?auto=format&fit=crop&w=1000&q=80" } }),
    prisma.product.upsert({ where: { sku: "SPL-002" }, update: {}, create: { sku: "SPL-002", slug: "orbit-9", name: "Orbit-9", description: "A hovering droid figure on a clear acrylic support rod, with a rotating sensor eye and glow-in-the-dark accents.", price: 12999, cost: 5900, stockQuantity: 10, categoryId: spaceLegends.id, franchise: "Space Legends", character: "Orbit-9", edition: "Exclusive", releaseDate: new Date("2026-06-18"), badges: ["LIMITED", "FAN_FAVORITE"], characterStory: "Orbit-9 was built to log soil samples and somehow developed a personality along the way, mostly sarcasm. It still logs the soil samples. It just has commentary now.", funFacts: ["Sensor eye rotates a full 360 degrees", "Accent panels glow in the dark after charging under light", "Its best voice lines only appear in the companion comic, not on the figure"], imageUrl: "https://images.unsplash.com/photo-1753492644538-53ee68625f6d?auto=format&fit=crop&w=1000&q=80" } }),
    prisma.product.upsert({ where: { sku: "SPL-003" }, update: {}, create: { sku: "SPL-003", slug: "nebula-reyes", name: "Nebula Reyes", description: "A field-suited explorer figure with a specimen case accessory and a translucent nebula-effect display base.", price: 15999, cost: 7200, stockQuantity: 5, categoryId: spaceLegends.id, franchise: "Space Legends", character: "Nebula Reyes", edition: "Chase", releaseDate: new Date("2026-08-15"), badges: ["PRE_ORDER", "LIMITED"], characterStory: "Nebula Reyes has cataloged more first-contact life forms than anyone alive, and keeps every single specimen jar labeled in her own careful handwriting. She's convinced the next jar will be the strange one.", funFacts: ["Display base uses swirled translucent resin, so no two are identical", "Specimen case opens to reveal three tiny sculpted samples", "Chase variant limited to 500 units worldwide"], imageUrl: "https://images.unsplash.com/photo-1603557092510-263cac6e7ae6?auto=format&fit=crop&w=1000&q=80" } }),

    // Kaiju Club
    prisma.product.upsert({ where: { sku: "KJC-001" }, update: {}, create: { sku: "KJC-001", slug: "grumblestone", name: "Grumblestone", description: "A boulder-textured kaiju figure with a soft-touch rubber hide and a surprisingly friendly under-bite grin.", price: 6999, cost: 3100, stockQuantity: 22, categoryId: kaijuClub.id, franchise: "Kaiju Club", character: "Grumblestone", edition: "Standard", releaseDate: new Date("2026-04-05"), badges: ["NEW"], characterStory: "Grumblestone flattened three city blocks on his first day and apologized to every single building. He just wanted to see the ocean. Now the city keeps a lane open for him.", funFacts: ["Textured hide uses a soft-touch rubber coating over hard plastic", "The grin was redesigned four times to look 'friendlier'", "Tail is a separate poseable piece"], imageUrl: "https://images.unsplash.com/photo-1623039902375-29258147f39e?auto=format&fit=crop&w=1000&q=80" } }),
    prisma.product.upsert({ where: { sku: "KJC-002" }, update: {}, create: { sku: "KJC-002", slug: "tidal-terror-marnie", name: "Tidal Terror Marnie", description: "A finned sea-kaiju figure with translucent teal accents and a wave-splash display base.", price: 9999, cost: 4500, stockQuantity: 12, categoryId: kaijuClub.id, franchise: "Kaiju Club", character: "Marnie", edition: "Deluxe", releaseDate: new Date("2026-05-28"), badges: ["FAN_FAVORITE"], characterStory: "Marnie surfaces once a year to redraw the coastline exactly how she likes it, then vanishes for another twelve months. Fishermen leave offerings. She mostly ignores them and takes the good boats anyway.", funFacts: ["Fins use a translucent two-tone plastic pour", "Splash base was sculpted from real wave-tank reference footage", "Second most requested figure in fan polls, right after Grumblestone"], imageUrl: "https://images.unsplash.com/photo-1608697341777-80b7461d93c3?auto=format&fit=crop&w=1000&q=80" } }),
    prisma.product.upsert({ where: { sku: "KJC-003" }, update: {}, create: { sku: "KJC-003", slug: "cinderjaw", name: "Cinderjaw", description: "A molten-cracked kaiju figure with heat-reactive color-shift paint across its back plates.", price: 13999, cost: 6300, stockQuantity: 7, categoryId: kaijuClub.id, franchise: "Kaiju Club", character: "Cinderjaw", edition: "Exclusive", releaseDate: new Date("2026-07-08"), badges: ["LIMITED", "PRE_ORDER"], characterStory: "Cinderjaw sleeps for decades at a time and wakes up furious about it every single time. The city has learned to just reschedule around him rather than argue.", funFacts: ["Back plates use color-shift paint that reacts to warm hands", "Sculpt required a custom mold just for the cracked-lava texture", "Exclusive to this release window only"], imageUrl: "https://images.unsplash.com/photo-1623039958673-08c3f4376009?auto=format&fit=crop&w=1000&q=80" } }),

    // Indie Artists
    prisma.product.upsert({ where: { sku: "IND-001" }, update: {}, create: { sku: "IND-001", slug: "marigold-the-tender", name: "Marigold the Tender", description: "A soft-sculpt art figure with a hand-painted floral wash finish, individually numbered on the base.", price: 7999, cost: 3600, stockQuantity: 18, categoryId: indieArtists.id, franchise: "Indie Artists", character: "Marigold", edition: "Standard", releaseDate: new Date("2026-03-18"), badges: ["NEW"], characterStory: "Marigold doesn't come from a franchise or a fight scene, just from an artist's sketchbook margin that got out of hand. She's meant to just sit somewhere quiet and be looked at.", funFacts: ["Each figure is individually numbered by hand", "Floral wash finish means no two are painted exactly alike", "First release from the studio's Indie Artists open-call program"], imageUrl: "https://images.unsplash.com/photo-1781543423089-dc61428dbbfa?auto=format&fit=crop&w=1000&q=80" } }),
    prisma.product.upsert({ where: { sku: "IND-002" }, update: {}, create: { sku: "IND-002", slug: "driftwood-dennis", name: "Driftwood Dennis", description: "A textured art-toy figure cast to resemble weathered driftwood, with a matte sealed finish and a cork display base.", price: 10999, cost: 4900, stockQuantity: 9, categoryId: indieArtists.id, franchise: "Indie Artists", character: "Dennis", edition: "Deluxe", releaseDate: new Date("2026-06-30"), badges: ["LIMITED", "FAN_FAVORITE"], characterStory: "Dennis started as a doodle of what furniture might look like if it got up and walked to the beach. The artist liked him too much to leave him as a sketch.", funFacts: ["Cork base is a real cork disc, not molded plastic", "Surface texture is hand-carved into the master sculpt", "Limited to one small-batch production run"], imageUrl: "https://images.unsplash.com/photo-1690041638795-14c34f90da9a?auto=format&fit=crop&w=1000&q=80" } }),
    prisma.product.upsert({ where: { sku: "IND-003" }, update: {}, create: { sku: "IND-003", slug: "static-bloom", name: "Static Bloom", description: "An abstract resin figure with a swirled, hand-poured colorway; no two castings share the exact same pattern.", price: 15999, cost: 7400, stockQuantity: 4, categoryId: indieArtists.id, franchise: "Indie Artists", character: "Static Bloom", edition: "Chase", releaseDate: new Date("2026-08-10"), badges: ["PRE_ORDER", "LIMITED"], characterStory: "Static Bloom isn't really a character at all, just a shape the artist kept returning to until it felt like one. Collectors have started giving her backstories of their own, and the studio has started listening.", funFacts: ["Hand-poured resin means every unit is a unique colorway", "Smallest production run in the entire catalog", "Studio now takes fan-submitted lore for future releases"], imageUrl: "https://images.unsplash.com/photo-1767026916692-aa8f9cd220ef?auto=format&fit=crop&w=1000&q=80" } }),

    // Mini Icons
    prisma.product.upsert({ where: { sku: "MNI-001" }, update: {}, create: { sku: "MNI-001", slug: "bitesize-bandit", name: "Bitesize Bandit", description: "A 3-inch blind-box mini with a mischievous grin, sold in a sealed box with a surprise colorway inside.", price: 1499, cost: 600, stockQuantity: 60, categoryId: miniIcons.id, franchise: "Mini Icons", character: "Bitesize Bandit", edition: "Standard", releaseDate: new Date("2026-04-22"), badges: ["NEW"], characterStory: "Bitesize Bandit steals one small thing from every desk he sits on, a pen cap, a paperclip, never anything you'd miss. Collectors swear their missing staplers are his fault.", funFacts: ["Sold blind-boxed, so the colorway is a surprise on opening", "1-in-24 chance of a secret rare colorway", "Smallest figure in the entire catalog at 3 inches tall"], imageUrl: "https://images.unsplash.com/photo-1762215643003-d6fb6fa4c777?auto=format&fit=crop&w=1000&q=80" } }),
    prisma.product.upsert({ where: { sku: "MNI-002" }, update: {}, create: { sku: "MNI-002", slug: "tiny-tempest", name: "Tiny Tempest", description: "A 4-inch mini figure with a swirled translucent-blue base meant to look like a captured gust of wind.", price: 1999, cost: 850, stockQuantity: 30, categoryId: miniIcons.id, franchise: "Mini Icons", character: "Tiny Tempest", edition: "Deluxe", releaseDate: new Date("2026-05-15"), badges: ["LIMITED"], characterStory: "Tiny Tempest is what happens when a much bigger storm spirit gets bottled down to desk size. She's still just as dramatic about it, just smaller.", funFacts: ["Translucent base uses the same resin process as the full-size Space Legends line", "Comes with a tiny cardboard 'storm warning' sign accessory", "Second entry in the Mini Icons elemental sub-series"], imageUrl: "https://images.unsplash.com/photo-1769345749373-d1407c84cdbf?auto=format&fit=crop&w=1000&q=80" } }),
    prisma.product.upsert({ where: { sku: "MNI-003" }, update: {}, create: { sku: "MNI-003", slug: "pocket-paladin", name: "Pocket Paladin", description: "A 4-inch armored mini with a removable cape and a die-cast metal sword accessory.", price: 2499, cost: 1100, stockQuantity: 16, categoryId: miniIcons.id, franchise: "Mini Icons", character: "Pocket Paladin", edition: "Exclusive", releaseDate: new Date("2026-07-29"), badges: ["FAN_FAVORITE", "PRE_ORDER"], characterStory: "Pocket Paladin takes his oath just as seriously as any full-size knight, even though he's small enough to guard a desk drawer. He has never once left his post.", funFacts: ["Sword accessory is die-cast metal, not plastic", "Cape is removable and interchangeable with other Mini Icons figures", "Most pre-ordered mini in line history"], imageUrl: "https://images.unsplash.com/photo-1720630351963-93567f7a746d?auto=format&fit=crop&w=1000&q=80" } }),
  ]);

  await prisma.customer.upsert({ where: { email: "demo@mercury.store" }, update: {}, create: { name: "Demo Customer", email: "demo@mercury.store", passwordHash: await bcrypt.hash("demo-password", 12), cart: { create: {} } } });
}
main().finally(() => prisma.$disconnect());
