import { PrismaClient } from "@prisma/client";
import bcrypt from "bcryptjs";

const prisma = new PrismaClient();
async function main() {
  const living = await prisma.category.upsert({ where: { slug: "living" }, update: {}, create: { name: "Living", slug: "living", description: "Objects for slower rooms" } });
  const lighting = await prisma.category.upsert({ where: { slug: "lighting" }, update: {}, create: { name: "Lighting", slug: "lighting", description: "Warm light for everyday rituals" } });
  const tableware = await prisma.category.upsert({ where: { slug: "tableware" }, update: {}, create: { name: "Tableware", slug: "tableware", description: "Tactile pieces for the table" } });
  const textiles = await prisma.category.upsert({ where: { slug: "textiles" }, update: {}, create: { name: "Textiles", slug: "textiles", description: "Layered comfort for every room" } });
  const audio = await prisma.category.upsert({ where: { slug: "audio" }, update: {}, create: { name: "Audio", slug: "audio", description: "Sound with a calmer presence" } });
  await Promise.all([
    prisma.product.upsert({ where: { sku: "ARC-001" }, update: {}, create: { sku: "ARC-001", slug: "arc-ceramic-speaker", name: "Arc Ceramic Speaker", description: "A compact speaker with a sculptural ceramic body.", price: 129900, cost: 67000, stockQuantity: 28, categoryId: living.id, imageUrl: "https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=1000&q=80" } }),
    prisma.product.upsert({ where: { sku: "HAL-204" }, update: {}, create: { sku: "HAL-204", slug: "halo-desk-lamp", name: "Halo Desk Lamp", description: "A soft, focused pool of light for every desk.", price: 69900, cost: 31000, stockQuantity: 18, categoryId: lighting.id, imageUrl: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=1000&q=80" } }),
    prisma.product.upsert({ where: { sku: "SBL-042" }, update: { imageUrl: "https://images.unsplash.com/photo-1592078615290-033ee584e267?auto=format&fit=crop&w=1200&q=85" }, create: { sku: "SBL-042", slug: "sable-throw", name: "Sable Throw", description: "A weighty woven throw in a deep, mineral neutral.", price: 45900, cost: 18000, stockQuantity: 14, categoryId: textiles.id, imageUrl: "https://images.unsplash.com/photo-1592078615290-033ee584e267?auto=format&fit=crop&w=1200&q=85" } }),
    prisma.product.upsert({ where: { sku: "MOR-118" }, update: {}, create: { sku: "MOR-118", slug: "morrow-side-table", name: "Morrow Side Table", description: "An oak side table with a quiet circular silhouette.", price: 189900, cost: 93000, stockQuantity: 7, categoryId: living.id, imageUrl: "https://images.unsplash.com/photo-1532323544230-7191fd51bc1b?auto=format&fit=crop&w=1000&q=80" } }),
    prisma.product.upsert({ where: { sku: "ORA-291" }, update: {}, create: { sku: "ORA-291", slug: "ora-vase", name: "Ora Vase", description: "Hand-finished stoneware for branches, stems, and bare shelves.", price: 34900, cost: 12000, stockQuantity: 31, categoryId: living.id, imageUrl: "https://images.unsplash.com/photo-1612196808214-b8e1d6145a8c?auto=format&fit=crop&w=1000&q=80" } }),
    prisma.product.upsert({ where: { sku: "LIN-062" }, update: {}, create: { sku: "LIN-062", slug: "linen-cushion", name: "Linen Cushion", description: "A tactile washed-linen cushion with a soft feather fill.", price: 29900, cost: 11000, stockQuantity: 22, categoryId: living.id, imageUrl: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=1000&q=80" } }),
    prisma.product.upsert({ where: { sku: "RIM-017" }, update: {}, create: { sku: "RIM-017", slug: "rim-stoneware-mug", name: "Rim Stoneware Mug", description: "A generous hand-finished mug with a raw clay rim.", price: 18900, cost: 7000, stockQuantity: 44, categoryId: tableware.id, imageUrl: "https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?auto=format&fit=crop&w=1000&q=80" } }),
    prisma.product.upsert({ where: { sku: "CIR-015" }, update: {}, create: { sku: "CIR-015", slug: "circle-serving-board", name: "Circle Serving Board", description: "Solid acacia board for bread, fruit, and long evenings.", price: 55900, cost: 26000, stockQuantity: 15, categoryId: tableware.id, imageUrl: "https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1000&q=80" } }),
    prisma.product.upsert({ where: { sku: "FLD-088" }, update: {}, create: { sku: "FLD-088", slug: "field-wool-rug", name: "Field Wool Rug", description: "A low-pile wool rug woven in a restrained graphic pattern.", price: 249900, cost: 125000, stockQuantity: 5, categoryId: textiles.id, imageUrl: "https://images.unsplash.com/photo-1600166898405-da9535204843?auto=format&fit=crop&w=1000&q=80" } }),
    prisma.product.upsert({ where: { sku: "NOM-301" }, update: {}, create: { sku: "NOM-301", slug: "nomad-floor-cushion", name: "Nomad Floor Cushion", description: "A structured floor cushion for reading, resting, and gathering.", price: 38900, cost: 17000, stockQuantity: 19, categoryId: textiles.id, imageUrl: "https://images.unsplash.com/photo-1618220179428-22790b461013?auto=format&fit=crop&w=1000&q=80" } }),
    prisma.product.upsert({ where: { sku: "WAV-903" }, update: {}, create: { sku: "WAV-903", slug: "wave-bluetooth-speaker", name: "Wave Bluetooth Speaker", description: "A compact wireless speaker with an oak and fabric enclosure.", price: 99900, cost: 49000, stockQuantity: 12, categoryId: audio.id, imageUrl: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&w=1000&q=80" } }),
  ]);
  await prisma.customer.upsert({ where: { email: "demo@mercury.store" }, update: {}, create: { name: "Demo Customer", email: "demo@mercury.store", passwordHash: await bcrypt.hash("demo-password", 12), cart: { create: {} } } });
}
main().finally(() => prisma.$disconnect());
