ALTER TABLE "StoreSettings" ADD COLUMN "heroModelRotationX" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "StoreSettings" ADD COLUMN "heroModelRotationZ" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "HeroPreset" ADD COLUMN "heroModelRotationX" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "HeroPreset" ADD COLUMN "heroModelRotationZ" DOUBLE PRECISION NOT NULL DEFAULT 0;
