"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { adminFetch } from "@/lib/adminApi";
import { formatMoney } from "@/lib/money";

type Category = { id: string; name: string; slug: string };
type Product = { id: string; sku: string; slug: string; name: string; price: number; stockQuantity: number; imageUrl: string | null; visible: boolean; categoryId: string; category: { name: string } };
type Order = { id: string; number: string; status: string; total: number; customer: { name: string; email: string } };
type Tab = "Overview" | "Catalog" | "Categories" | "Inventory" | "Orders";
type IconName = "grid" | "box" | "tag" | "bars" | "truck" | "plus" | "search" | "arrow" | "menu" | "close";

const icons: Record<IconName, string> = {
  grid: "M4 4h6v6H4zM14 4h6v6h-6zM4 14h6v6H4zM14 14h6v6h-6z", box: "M3 7.5 12 3l9 4.5v9L12 21l-9-4.5v-9ZM3.5 7.8 12 12l8.5-4.2M12 12v9", tag: "M20 13 13 20 4 11V4h7l9 9ZM8 8h.01", bars: "M5 19V9m7 10V5m7 14v-6", truck: "M3 5h11v11H3zM14 9h4l3 3v4h-7zM7 19a2 2 0 1 0 0-4 2 2 0 0 0 0 4Z", plus: "M12 5v14M5 12h14", search: "m20 20-4.4-4.4M10.8 18a7.2 7.2 0 1 1 0-14.4 7.2 7.2 0 0 1 0 14.4Z", arrow: "M5 12h14m-6-6 6 6-6 6", menu: "M4 7h16M4 12h16M4 17h16", close: "M6 6l12 12M18 6 6 18",
};
function Icon({ name }: { name: IconName }) { return <svg className="adminIcon" viewBox="0 0 24 24" aria-hidden="true"><path d={icons[name]} /></svg>; }
const nav: [Tab, IconName][] = [["Overview", "grid"], ["Catalog", "box"], ["Categories", "tag"], ["Inventory", "bars"], ["Orders", "truck"]];
const copy: Record<Tab, [string, string, string]> = { Overview: ["01 — THE EDIT", "A calmer way to run commerce.", "The important work, at a glance."], Catalog: ["02 — OBJECTS", "Your catalog.", "Keep every object clear, considered, and ready to sell."], Categories: ["03 — COLLECTIONS", "Shape the browse.", "Give customers a simple way to find what they came for."], Inventory: ["04 — AVAILABILITY", "Stock, in view.", "Make small adjustments before they become big problems."], Orders: ["05 — DELIVERY", "On its way.", "Keep every customer informed from packing to doorstep."] };

export default function AdminWorkspace() {
  const [tab, setTab] = useState<Tab>("Overview");
  const [products, setProducts] = useState<Product[]>([]);
  const [categories, setCategories] = useState<Category[]>([]);
  const [orders, setOrders] = useState<Order[]>([]);
  const [query, setQuery] = useState(""), [modal, setModal] = useState<"product" | "category" | null>(null), [menuOpen, setMenuOpen] = useState(false), [notice, setNotice] = useState("");

  async function loadAll() {
    const [productList, categoryList, orderList] = await Promise.all([adminFetch<Product[]>("/api/admin/products"), adminFetch<Category[]>("/api/admin/categories"), adminFetch<Order[]>("/api/admin/orders")]);
    setProducts(productList); setCategories(categoryList); setOrders(orderList);
  }
  useEffect(() => { loadAll().catch(() => setNotice("Could not load workspace data.")); }, []);

  const metrics = useMemo(() => ({ stock: products.reduce((sum, item) => sum + item.stockQuantity, 0), low: products.filter((item) => item.stockQuantity < 10).length }), [products]);
  const visibleProducts = products.filter((item) => `${item.name} ${item.sku} ${item.category.name}`.toLowerCase().includes(query.toLowerCase()));
  const navigate = (next: Tab) => { setTab(next); setMenuOpen(false); setQuery(""); };

  async function addProduct(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const data = new FormData(event.currentTarget);
    const name = String(data.get("name") || "New product");
    const slug = name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
    try { await adminFetch("/api/admin/products", { method: "POST", body: JSON.stringify({ name, sku: `NEW-${Date.now().toString().slice(-6)}`, slug, description: `${name}, a considered addition to the collection.`, categoryId: String(data.get("category")), price: Math.round(Number(data.get("price") || 0) * 100), cost: 0, stockQuantity: Number(data.get("stock") || 0) }) }); await loadAll(); setModal(null); navigate("Catalog"); setNotice(`${name} was added.`); } catch { setNotice("Could not add that product."); }
  }
  async function addCategory(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const name = String(new FormData(event.currentTarget).get("category") || "").trim();
    const slug = name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
    if (!name) { setNotice("Enter a category name."); return; }
    try { await adminFetch("/api/admin/categories", { method: "POST", body: JSON.stringify({ name, slug }) }); await loadAll(); setModal(null); setNotice(`${name} was added.`); } catch { setNotice("Could not add that collection."); }
  }
  async function adjust(product: Product, amount: number) {
    try { await adminFetch("/api/admin/inventory", { method: "POST", body: JSON.stringify({ productId: product.id, delta: amount, reason: amount > 0 ? "Manual restock" : "Manual adjustment" }) }); await loadAll(); setNotice(`${amount > 0 ? "Added" : "Removed"} ${Math.abs(amount)} item${Math.abs(amount) === 1 ? "" : "s"} of stock for ${product.name}.`); } catch { setNotice("Could not adjust stock."); }
  }
  async function advance(order: Order) {
    const steps: Record<string, string> = { PENDING: "CONFIRMED", CONFIRMED: "PACKED", PACKED: "SHIPPED", SHIPPED: "DELIVERED" };
    const status = steps[order.status];
    if (!status) return;
    try { await adminFetch("/api/admin/orders", { method: "PATCH", body: JSON.stringify({ orderId: order.id, status, ...(status === "SHIPPED" ? { trackingCode: "TRK-DEMO" } : {}) }) }); await loadAll(); setNotice(`Order ${order.number} moved to ${status.toLowerCase()}.`); } catch { setNotice("Could not advance that order."); }
  }

  return <main className="adminShell"><aside className={`adminSidebar ${menuOpen ? "isOpen" : ""}`}><button className="adminBrand" onClick={() => navigate("Overview")}>SOAR<span>°</span><small>commerce</small></button><p className="adminSectionLabel">OPERATIONS</p><nav className="adminNav" aria-label="Workspace sections">{nav.map(([label, icon]) => <button key={label} className={tab === label ? "active" : ""} onClick={() => navigate(label)}><Icon name={icon} />{label}{label === "Orders" && <b>{orders.filter((order) => order.status !== "DELIVERED").length}</b>}</button>)}</nav><div className="adminSidebarFoot"><span className="adminAvatar">AK</span><div><strong>Ansh Kumar</strong><small>Administrator</small></div></div></aside><section className="adminPage"><header className="adminTopbar"><button className="mobileMenu" aria-label="Toggle navigation" onClick={() => setMenuOpen(!menuOpen)}><Icon name={menuOpen ? "close" : "menu"} /></button><p>SOAR / ADMIN</p><div><span className="adminStatusDot" />System ready</div></header><div className="adminContent"><section className="adminIntro"><div><p className="adminKicker">{copy[tab][0]}</p><h1>{copy[tab][1]}</h1><p className="adminLead">{copy[tab][2]}</p></div>{tab === "Catalog" || tab === "Overview" ? <button className="adminPrimary" onClick={() => setModal("product")}><Icon name="plus" />Add product</button> : tab === "Categories" ? <button className="adminPrimary" onClick={() => setModal("category")}><Icon name="plus" />Add collection</button> : null}</section>{notice && <div className="adminNotice" role="status">{notice}<button aria-label="Dismiss" onClick={() => setNotice("")}>×</button></div>}{tab === "Overview" && <Overview products={products} orders={orders} metrics={metrics} onNavigate={navigate} onAdvance={advance} />}{tab === "Catalog" && <Catalog products={visibleProducts} query={query} onQuery={setQuery} onOpen={() => setModal("product")} />}{tab === "Categories" && <Categories categories={categories} products={products} onAdd={() => setModal("category")} />}{tab === "Inventory" && <Inventory products={visibleProducts} query={query} onQuery={setQuery} onAdjust={adjust} />}{tab === "Orders" && <Orders orders={orders} onAdvance={advance} />}</div></section>{modal === "product" && <ProductModal categories={categories} onClose={() => setModal(null)} onSave={addProduct} />}{modal === "category" && <CategoryModal onClose={() => setModal(null)} onSave={addCategory} />}</main>;
}

function Overview({ products, orders, metrics, onNavigate, onAdvance }: { products: Product[]; orders: Order[]; metrics: { stock: number; low: number }; onNavigate: (tab: Tab) => void; onAdvance: (order: Order) => void }) { return <><section className="adminStats"><article><span>Orders to fulfil</span><strong>{String(orders.filter((order) => order.status !== "DELIVERED").length).padStart(2, "0")}</strong><small>Orders awaiting a handoff</small></article><article><span>In stock</span><strong>{metrics.stock}</strong><small>{metrics.low} objects need attention</small></article><article><span>Catalog size</span><strong>{products.length}</strong><small>objects listed</small></article></section><section className="adminBlockHeading"><div><p className="adminKicker">AT A GLANCE</p><h2>Objects needing attention</h2></div><button onClick={() => onNavigate("Inventory")}>View inventory <Icon name="arrow" /></button></section><section className="adminFeatureGrid">{products.filter((product) => product.stockQuantity < 10).slice(0, 3).map((product) => <ProductCard product={product} key={product.id} />)}</section><section className="adminBlockHeading adminOrdersHeading"><div><p className="adminKicker">FULFILMENT</p><h2>Move today's orders</h2></div><button onClick={() => onNavigate("Orders")}>All orders <Icon name="arrow" /></button></section><div className="adminOrderList">{orders.slice(0, 2).map((order) => <OrderRow order={order} key={order.id} onAdvance={onAdvance} />)}</div></>; }
function Catalog({ products, query, onQuery, onOpen }: { products: Product[]; query: string; onQuery: (value: string) => void; onOpen: () => void }) { return <><div className="adminToolbar"><label><Icon name="search" /><input value={query} onChange={(event) => onQuery(event.target.value)} placeholder="Search name or SKU" /></label><span>{products.length} objects</span><button className="adminTextButton" onClick={onOpen}>+ New object</button></div><section className="adminCatalogGrid">{products.map((product) => <ProductCard product={product} key={product.id} />)}{products.length === 0 && <div className="adminEmpty">No objects match that search.</div>}</section></>; }
function Categories({ categories, products, onAdd }: { categories: Category[]; products: Product[]; onAdd: () => void }) { return <section className="adminCollectionGrid">{categories.map((category, index) => <article key={category.id}><span>0{index + 1}</span><h2>{category.name}</h2><p>{products.filter((product) => product.categoryId === category.id).length} objects in this collection</p><button onClick={onAdd}>Add another <Icon name="arrow" /></button></article>)}<button className="adminAddCollection" onClick={onAdd}><Icon name="plus" />Create a collection</button></section>; }
function Inventory({ products, query, onQuery, onAdjust }: { products: Product[]; query: string; onQuery: (value: string) => void; onAdjust: (product: Product, amount: number) => void }) { return <><div className="adminToolbar"><label><Icon name="search" /><input value={query} onChange={(event) => onQuery(event.target.value)} placeholder="Find an object" /></label><span>Every change writes an audit entry</span></div><section className="adminTable"><div className="adminTableHeader"><span /><span>Object</span><span>Available</span><span>Adjust</span></div>{products.map((product) => <div className="adminStockRow" key={product.id}><span className="iconTile"><Icon name="box" /></span><div><strong>{product.name}</strong><small>{product.sku} · {product.category.name}</small></div><b className={product.stockQuantity < 10 ? "lowStock" : ""}>{product.stockQuantity} <small>in stock</small></b><div className="adminStepper"><button onClick={() => onAdjust(product, -1)} aria-label={`Remove one ${product.name}`}>−</button><button onClick={() => onAdjust(product, 1)} aria-label={`Add one ${product.name}`}>+</button></div></div>)}</section></>; }
function Orders({ orders, onAdvance }: { orders: Order[]; onAdvance: (order: Order) => void }) { return <section className="adminOrderList adminOrderPage">{orders.map((order) => <OrderRow order={order} key={order.id} onAdvance={onAdvance} />)}</section>; }
function OrderRow({ order, onAdvance }: { order: Order; onAdvance: (order: Order) => void }) { return <article className="adminOrderRow"><span className="iconTile"><Icon name="truck" /></span><div><p>{order.number}</p><strong>{order.customer.name}</strong></div><span>{formatMoney(order.total)}</span><i className={`orderStatus ${order.status.toLowerCase()}`}>{order.status}</i><button disabled={order.status === "DELIVERED"} onClick={() => onAdvance(order)}>{order.status === "DELIVERED" ? "Complete" : "Advance"}<Icon name="arrow" /></button></article>; }
function ProductCard({ product }: { product: Product }) { return <article className="adminProductCard"><div className="adminProductImage">{product.imageUrl ? <img src={product.imageUrl} alt="" /> : <Icon name="box" />}</div><div className="adminProductMeta"><div><span>{product.category.name}</span><i className={product.visible ? "productLive" : "productDraft"}>{product.visible ? "Live" : "Draft"}</i></div><h3>{product.name}</h3><p>{product.sku} · {formatMoney(product.price)}</p><footer><strong className={product.stockQuantity < 10 ? "lowStock" : ""}>{product.stockQuantity} in stock</strong></footer></div></article>; }
function ProductModal({ categories, onClose, onSave }: { categories: Category[]; onClose: () => void; onSave: (event: FormEvent<HTMLFormElement>) => void }) { return <div className="adminModalBack"><form className="adminModal" onSubmit={onSave}><button type="button" className="adminModalClose" onClick={onClose}><Icon name="close" /></button><p className="adminKicker">NEW OBJECT</p><h2>Add something considered.</h2><label>Name<input name="name" required placeholder="Object name" /></label><label>Collection<select name="category">{categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label><div className="adminModalPair"><label>Price (₹)<input name="price" type="number" required min="0" step="0.01" placeholder="0.00" /></label><label>Starting stock<input name="stock" type="number" required min="0" placeholder="0" /></label></div><button className="adminPrimary" type="submit">Add object <Icon name="arrow" /></button></form></div>; }
function CategoryModal({ onClose, onSave }: { onClose: () => void; onSave: (event: FormEvent<HTMLFormElement>) => void }) { return <div className="adminModalBack"><form className="adminModal" onSubmit={onSave}><button type="button" className="adminModalClose" onClick={onClose}><Icon name="close" /></button><p className="adminKicker">NEW COLLECTION</p><h2>Make a place for it.</h2><label>Collection name<input name="category" required placeholder="e.g. Desk objects" /></label><button className="adminPrimary" type="submit">Create collection <Icon name="arrow" /></button></form></div>; }
