import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { customerFromRequest } from "@/lib/auth";
import { error } from "@/lib/api";
import { prisma } from "@/lib/prisma";
const input = z.object({ productId: z.string(), quantity: z.number().int().min(1).max(99), collectionId: z.string().optional() });
export async function GET(request: NextRequest) { const session = await customerFromRequest(request); if (!session) return error("Sign in required", 401); const cart = await prisma.cart.findUnique({ where: { customerId: session.customerId }, include: { items: { include: { product: true } } } }); return NextResponse.json(cart); }
// collectionId tags a line as part of a bundle "add all to bag" click; a plain add (no collectionId) always
// clears any previous tag, matching the existing last-write-wins behaviour this route already had for quantity.
export async function POST(request: NextRequest) { const session = await customerFromRequest(request); if (!session) return error("Sign in required", 401); const parsed = input.safeParse(await request.json()); if (!parsed.success) return error(parsed.error.issues[0].message, 400); const product = await prisma.product.findFirst({ where: { id: parsed.data.productId, visible: true } }); if (!product) return error("Product not found", 404); if (product.stockQuantity < parsed.data.quantity) return error("Not enough stock", 409); const cart = await prisma.cart.upsert({ where: { customerId: session.customerId }, create: { customerId: session.customerId }, update: {} }); const collectionId = parsed.data.collectionId ?? null; await prisma.cartItem.upsert({ where: { cartId_productId: { cartId: cart.id, productId: product.id } }, create: { cartId: cart.id, productId: product.id, quantity: parsed.data.quantity, collectionId }, update: { quantity: parsed.data.quantity, collectionId } }); return NextResponse.json({ ok: true }); }
export async function DELETE(request: NextRequest) { const session = await customerFromRequest(request); if (!session) return error("Sign in required", 401); const cart = await prisma.cart.findUnique({ where: { customerId: session.customerId } }); if (cart) await prisma.cartItem.deleteMany({ where: { cartId: cart.id } }); return NextResponse.json({ ok: true }); }
