-- AlterTable
ALTER TABLE "StoreSettings" ADD COLUMN     "heroBoxLine" TEXT NOT NULL DEFAULT 'ANIMATION',
ADD COLUMN     "heroBoxNumber" TEXT NOT NULL DEFAULT '1000',
ADD COLUMN     "heroBoxBanner" TEXT NOT NULL DEFAULT 'DEMON SLAYER',
ADD COLUMN     "heroBoxName" TEXT NOT NULL DEFAULT 'TANJIRO',
ADD COLUMN     "heroBoxSubtitle" TEXT NOT NULL DEFAULT 'WITH NOODLES';
